version: '3.8'

services:
  # Serviço 1: Sua API (FastAPI)
  backend:
    build: .
    container_name: sigma_backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app  # Sincroniza sua pasta com o Docker (mudou código aqui, muda lá)
    ports:
      - "8000:8000"

  # Serviço 2: Seu Site (Streamlit)
  frontend:
    build: .
    container_name: sigma_frontend
    command: streamlit run app.py
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000 # O Front fala com o Back pelo nome do serviço
    depends_on:
      - backend